<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertGemStones extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $gem_categories = App\Models\GemCategory::all()->pluck("id", "name");

        \Illuminate\Support\Facades\DB::table('gem_stones')
            ->insert([
                ['name' => 'Agni Mani', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Schwarzer Tektit (Glasstückchen)'],
                ['name' => 'Alge', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Quarzart mit dunkelbraunem Wellenmuster'],
                ['name' => 'Augelit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Klarer, farbloser Kristall'],
                ['name' => 'Augenachat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Graue, weiße, braune, graublaue und gelblich graugrüne Ringe'],
                ['name' => 'Azurit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Tiefblau, mit undurchsichtigen Flecken in dunkleren Blautönen'],
                ['name' => 'Blauer Quarz', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Durchsichtiger, hellblauer Kristall'],
                ['name' => 'Blaustein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Tiefblau, weich, brüchig. Rosafarbene, weiße, cremefarbene und gelbe Adern'],
                ['name' => 'Bünderachat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Undurchsichtiger Quarz mit gerieften braunen, roten, blauen und weißen Streifen'],
                ['name' => 'Chrysocolla', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Blaugrün bis grün gefärbte Abart des Kalzedon'],
                ['name' => 'Corstal', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Farbloser bis rosafarbener Kristall, hart, brüchig, mit Einschlüssen'],
                ['name' => 'Disthen', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Kristall, dunkelblau bis blaßgrün'],
                ['name' => 'Elfenbein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Geschliffen, poliert, weiß'],
                ['name' => 'Epidot', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Kristall, klar oder dunkles rot, selten tiefes rosa'],
                ['name' => 'Feuerachat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Durchscheinend, schillernd rot, braun, golden oder grüner Kalzedon'],
                ['name' => 'Flurspat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Hellblau, grün, gelb, purpurn, rosa, rot, weich'],
                ['name' => 'Frostachat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Weiße Flecken'],
                ['name' => 'Gestreifter Achat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Gestreift'],
                ['name' => 'Glanz', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Obsidianart, mahagoni bis silberfarben'],
                ['name' => 'Goldlinie', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Quarz mit goldfarbenen Linien'],
                ['name' => 'Grünstein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Graugrün, weich'],
                ['name' => 'Hämatit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Glänzend, grauschwarz'],
                ['name' => 'Holzzinke', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Bräunlich, fibrös'],
                ['name' => 'Hyalin', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Milchiger oder weißer Quarz, oft goldgesprenkelt'],
                ['name' => 'Lapislazuli', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Undurchsichtig, dunkelblau mit Goldflecken'],
                ['name' => 'Luchsauge', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Hell- bis dunkelgrau, bunt schimmernde blaue Flecken'],
                ['name' => 'Malachit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Grün mit dunklen grünen Riefen'],
                ['name' => 'Mikroklin', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Dunkelgrün bis blaugrün, zebrechlich'],
                ['name' => 'Moosachat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Rosa, gelblich weiß mit graugrünen, moosähnlichen Flecken'],
                ['name' => 'Nelvin', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Weiß, cremefarbig, beige oder braun-rosa mit blauem Schillern, weich, zerbrechlich'],
                ['name' => 'Netzstein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Schwarz mit weißen Linien, manchmal auch braun, rötlichbraun und rostrot'],
                ['name' => 'Nune', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Durchscheinend, braun oder fast klar'],
                ['name' => 'Obsidian', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Hart, glänzend, schwarz, vulkanischen Ursprungs'],
                ['name' => 'Oolit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Dunkelbraun, Quarzart'],
                ['name' => 'Ophealin', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Braun oder violett'],
                ['name' => 'Rhodokrosit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Durchscheinend, rosa mit glasartigem Leuchten'],
                ['name' => 'Rosalin', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Weich oder hart, dreifarbig, purpur/blau/rot oder purpur/grün/rot'],
                ['name' => 'Sagenit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Elfenbeinfarben oder gelb mit braunen oder grünlich schwarzen Nadeln'],
                ['name' => 'Sanidin', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Blassbraun bis strohgelb'],
                ['name' => 'Sarbossa', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Hart oder weich, gräulich grün, manchmal rosa, rot, weiß oder grüne Ringe'],
                ['name' => 'Scharfstein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Quarzart, verschiedene Farben'],
                ['name' => 'Schneeflockenobsidian', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Schwarz, gräuliche blumenartige Flecken, brüchig'],
                ['name' => 'Seidenspat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Weich, weiß, pink, blaßorange oder blaßbraun'],
                ['name' => 'Seidenstein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Schwach glitzernd, meistens gelb'],
                ['name' => 'Silberkrone', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Silbern glänzend'],
                ['name' => 'Sonnenstein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Farblos oder leicht grünlich, weich'],
                ['name' => 'Süßwasserperle', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Ungleichmäßig'],
                ['name' => 'Tigeraugenachat', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Golden mit dunkelbraunen Streifen'],
                ['name' => 'Türkis', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Grünblau mit dunkleren Sprenkeln'],
                ['name' => 'Turmalin', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Hart, tiefgrün, blaß grünliches gelb oder gelb bis braun, durchscheinend'],
                ['name' => 'Variscit', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Durchscheinend, tiefes bis blaßgelbliches grün'],
                ['name' => 'Violan', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Purpur, vulkangestein'],
                ['name' => 'Wunderstein', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Rote, braune, lohfarbene oder purpurne Bänder'],
                ['name' => 'Zarbrina', 'gem_category_id' => $gem_categories['Zierstein'], 'cost' => '10', 'description' => 'Weich, farblos'],
                ['name' => 'Andar', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Grünrot oder braunrot, durchsichtig, hart'],
                ['name' => 'Aventurin', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Golden, mittel- bis hellgrün oder dunkel- bis blassblau mit glitzernden Kristallen besetzt'],
                ['name' => 'Bergkristall', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Klar, durchscheinend, weich'],
                ['name' => 'Bierstein', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Braun bis gelbbraun'],
                ['name' => 'Blutstein', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Dunkle, grünlichgraue Quarzart mit roten Kristallflecken gesprenkelt'],
                ['name' => 'Boakhar', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Weich, zerbrechlich, rot oder orange'],
                ['name' => 'Chrysopras', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Durchscheinend, apfel- bis smaragdgrün'],
                ['name' => 'Clelophan', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Blaßgrün, durchsichtig, weich, zerbrechlich'],
                ['name' => 'Datchas', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Blass, gelblich grün'],
                ['name' => 'Dioptas', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Weich, brüchig, smaragdgrün'],
                ['name' => 'Goldglanz', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Golden, mit winzigen Sprengseln, brüchig'],
                ['name' => 'Hambergyl', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Farblos, hart'],
                ['name' => 'Himmelstropfen', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Klar, hell'],
                ['name' => 'Hydrophan', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Frostigweiß oder elfenbeinfarben'],
                ['name' => 'Hypersthen', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Braun, manchmal rötlich oder grünlich, silberne Sprengsel'],
                ['name' => 'Iol', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Farbwechselnd strohgelb, blau oder dunkelblau'],
                ['name' => 'Irtios', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Hart, transparent, blaßgelb oder farblos'],
                ['name' => 'Jaspis', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Rot, braun, schwarz, manchmal blau oder nur blaue Bänder'],
                ['name' => 'Kalzedon', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Weiß, durchscheinend, manchmal auch grau oder schwarz'],
                ['name' => 'Karneol', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Rötlich oder rotbraun'],
                ['name' => 'Luriyl', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Weich, gelb, grün, gelbgrün, selten blau oder purpur'],
                ['name' => 'Malacon', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Glasigbraun, hart, splittern leicht'],
                ['name' => 'Mellochrysos', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Gelb, hart'],
                ['name' => 'Mondstein', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Weiß mit blaßblauem Schimmer'],
                ['name' => 'Mykaro', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Gelb, strohgelb, blaßbrau, rötlichbraun, grün, blau, blaugrün, weich, zäh'],
                ['name' => 'Mynteer', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Hart, farblos'],
                ['name' => 'Onyx', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Schwarz, weiß oder beidfarbig gestreift'],
                ['name' => 'Orpras', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Farblos oder schwach strohgelb, brüchig'],
                ['name' => 'Phenalop', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Rosenrot oder rosa'],
                ['name' => 'Porphyr', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Rosarot oder pink'],
                ['name' => 'Rauchquarz', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Hellgrau, -gelb, -braun oder -blau'],
                ['name' => 'Regenbogenobsidian', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Schwarz oder grau, farbliche Streifen außer gelb, hart, brüchig'],
                ['name' => 'Rosenquarz', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Trübrosa mit weißem, sternförmigen Zentrum'],
                ['name' => 'Samarskit', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Hart, samtschwarz'],
                ['name' => 'Sardonyx', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Rote und weiße Streifen'],
                ['name' => 'Schlangenstein', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Reines grün'],
                ['name' => 'Spodumen', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Rose bis purpur, manchmal auch smaragdgrün, hart'],
                ['name' => 'Sternrosenquarz', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Rauchiger Quarz mit Sternstruktur'],
                ['name' => 'Tabasheer', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Samtweicher Glanz'],
                ['name' => 'Tchazar', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Strohgelb, weich, zerbrechlich'],
                ['name' => 'Witherit', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Blaßgelb, weiß'],
                ['name' => 'Zirkon', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Klar blaßblau'],
                ['name' => 'Zitrin', 'gem_category_id' => $gem_categories['Halbedelstein'], 'cost' => '50', 'description' => 'Blass gelbbraun'],
                ['name' => 'Alexandrit', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Dunkelgrün'],
                ['name' => 'Amethyst', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Purpurrot kristallen'],
                ['name' => 'Bernstein', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Durchscheinend golden, weich, brüchig'],
                ['name' => 'Brandeen', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Rötlichbraun bis honiggelb'],
                ['name' => 'Chrysoberyll', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Grün oder gelbgrün, hart, transparent'],
                ['name' => 'Engelshaut', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Rosafarbene Koralle, lichtundurchlässig, zerbrechlich'],
                ['name' => 'Jade', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Hell- bis dunkelgrün oder weiß, wachsartig'],
                ['name' => 'Jargoon', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Rot, glänzend'],
                ['name' => 'Jet', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Tiefschwarz'],
                ['name' => 'Koralle', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Rosa bis hochrot'],
                ['name' => 'Kornerupin', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Hart, grün oder braun, durchscheinend'],
                ['name' => 'Laerals Träne', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Farblos, kristallin, weich, brüchig'],
                ['name' => 'Oktel', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Weich, blaßgelb oder orange'],
                ['name' => 'Pechstein', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Tiefschwarz'],
                ['name' => 'Scapra', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'blaßgelb oder mittelgelb, weich'],
                ['name' => 'Shandon', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Farbloser Kristall'],
                ['name' => 'Sinhalit', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Bleich, strohgelb bis gelbbraun'],
                ['name' => 'Sternendiopsid', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Dunkelgrün oder blaßgrün'],
                ['name' => 'Tremair', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Pink, klar'],
                ['name' => 'Ulvaen', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Weich, blaß- oder tiefgelb'],
                ['name' => 'Wasserstern', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Farblos, glitzernd'],
                ['name' => 'Zios', 'gem_category_id' => $gem_categories['Schmuckstein'], 'cost' => '100', 'description' => 'Purpur/blau/rot oder purpur/grün/rot'],
                ['name' => 'Aquamarin', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Blaugrün, hart, transparent'],
                ['name' => 'Euklas', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Farblos bis blaßgelb, tiefgelb, blaßgrün und blau'],
                ['name' => 'Flammentanz', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Kleine Kristalle'],
                ['name' => 'Granat', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Tiefrot bis violett'],
                ['name' => 'Heliodor', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Tiefgelb, grünlich gelb bis zu rötlich gelb'],
                ['name' => 'Hornkoralle', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Tiefschwarz'],
                ['name' => 'Olivin', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Olivgrün'],
                ['name' => 'Orbalin', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Weich, blau oder farblos'],
                ['name' => 'Perle', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Weiß, manchmal schwarz oder regenbogenfarben'],
                ['name' => 'Regentropfen', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Dunkelbraun, hart'],
                ['name' => 'Rusteen', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Dunkles rotbraun bis zu blaßbraun'],
                ['name' => 'Sphene', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Weich, brüchig, gelb bis grün'],
                ['name' => 'Spinel', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Rot oder blau, selten grün'],
                ['name' => 'Topas', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '500', 'description' => 'Goldgelb, transparent, hart'],
                ['name' => 'Feueropal', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Leuchtend orangerot, einfarbig oder mit goldenen oder grünen Einsprengseln'],
                ['name' => 'Grabjade (Gruftjade)', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Rot oder braun'],
                ['name' => 'Jasmal', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Durchscheinend, farblos, hart'],
                ['name' => 'Korund', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Feurig gelb oder tiefviolett'],
                ['name' => 'Mondbarren', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Milchig, perlweiß, groß'],
                ['name' => 'Opal', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Milchig, glatt, blaßblau mit grünen und goldenen Sprenkeln'],
                ['name' => 'Orblen (Honigstein)', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Tiefgolden, groß'],
                ['name' => 'Orient. Amethyst', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Tiefes Purpur'],
                ['name' => 'Orient. Topas', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Feurig gelb'],
                ['name' => 'Orl', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Rot, gelbraun oder orange'],
                ['name' => 'Ravenar', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Glänzend schwarz'],
                ['name' => 'Rote Träne', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Kräftig kirschrot, blutrot oder feurig orange, tränenförmig, glänzend'],
                ['name' => 'Saphir', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Klar bis mittelblau, durchscheinend'],
                ['name' => 'Schwarzer Opal', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Dunkelgrün mit schwarzen Sprenkeln und goldenen Flecken'],
                ['name' => 'Wasseropal', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Klar, durchscheinend'],
                ['name' => 'Zendalur', 'gem_category_id' => $gem_categories['Edelstein'], 'cost' => '1.000', 'description' => 'Blauweiß gefleckt'],
                ['name' => 'Amaratha', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Weich, grünlich-weiß oder blaßgrün, funkelnd'],
                ['name' => 'Beljuril', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Meerwassergrün, hart'],
                ['name' => 'Diamant', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Harte durchscheinende Steine in klarem Blauweiß, leuchtend blau, gelb oder rosa'],
                ['name' => 'Hyazinth (Jacinth)', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Feurig orange, im Herzen des Steins flackert eine kleine Flamme'],
                ['name' => 'Königsträne', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Klar, tränenförmig, außergewöhnlich hart'],
                ['name' => 'Orient. Smaragd', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Leuchtend grün'],
                ['name' => 'Rubin', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Klar bis tief karminrot, funkelnd leuchtend, sprühende Färbung'],
                ['name' => 'Schurkenstein', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Kleine Sterne, regenbogenfarben'],
                ['name' => 'Schwarzer Saphir', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Sattschwarz mit weißen oder gelben Einsprengseln'],
                ['name' => 'Smaragd', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => 'Strahlend grün'],
                ['name' => 'Sternrubin', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => '"Durchscheinend rubinrot mit weißem, sternförmigen "Licht"'],
                ['name' => 'Sternsaphir', 'gem_category_id' => $gem_categories['Juwel'], 'cost' => '5.000', 'description' => '"Durchscheinend blau mit weißem, sternförmigen "Licht"'],
            ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
